### ISSUE TITLE
内存波动太大了,不好用

### ISSUE THREAD

**Issue by mudao** [fanrunqi/WaveProgressView#15]
内存中不断画图,又释放.

**Comment by yazhi1992** [comment]
@mudao @fanrunqi 因为在onDraw里不断地去createBitmap，会造成严重的内存消耗，而且重点是在这里bitmap是没有必要不断重新构造的。
有兴趣可以参考下我的实现：https://github.com/yazhi1992/Practice/blob/master/app/src/main/java/com/yazhi1992/practice/wave_view/WaveView.java
