### ISSUE TITLE
Leak memory

### ISSUE THREAD

**Issue by Mojtaba-Shafaei** [fanrunqi/WaveProgressView#16]
Hi,i have a leak memory on WaveProgressView , because the Handler that used in WaveProgressView.java class had not release on detaching view.

this is LeakCanary message :
D/LeakCanary: * references cn.fanrunqi.waveprogress.WaveProgressView$1.this$0 (anonymous subclass of android.os.Handler)

**Comment by Simonida** [comment]
I've detected the same problem.

How to avoid this behavior?

**Comment by Mojtaba-Shafaei** [comment]
WaveProgressView keeps an instance of context. so this is cause of leak memory. 
If WaveProgressView has a method, we will call it to delete context variable on onDestrot() method
