### ISSUE TITLE
App leaks

### ISSUE THREAD

**Issue by qurrelito** [fanrunqi/WaveProgressView#22]
private Handler handler = new Handler() {
        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            switch (msg.what) {
                case INVALIDATE:
                    invalidate();
                    sendEmptyMessageDelayed(INVALIDATE,RefreshGap);
                    break;
            }
        }
    };

**Comment by fanrunqi** [comment]
Would you help me with this?

**Comment by qurrelito** [comment]
You don't need to create your own handler. View class already have that. So you can use .post or .postdelayed directly on the view instead. 

So, remove this:

private Handler handler = new Handler() {
@override
public void handleMessage(Message msg) {
super.handleMessage(msg);
switch (msg.what) {
case INVALIDATE:
invalidate();
sendEmptyMessageDelayed(INVALIDATE,RefreshGap);
break;
}
}
};

/Q
