### ISSUE TITLE
How do I reset the ProgressView?

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [fanrunqi/WaveProgressView#6]
I am trying to use the WaveProgressView for the progress of a timer. But I am not sure how to reset the progress to empty once it is full?

**Comment by fpasxos** [comment]
What about this one :
`switch (msg.what) {
                case one:
                    if (progress <= 100) {
                        waveProgressbar.setCurrent(progress, progress + "%");
                        sendEmptyMessageDelayed(one, 100);
                    }
                    else{
                        waveProgressbar.setVisibility(View.GONE);
                        waveProgressbar.setVisibility(View.VISIBLE);

                        progress = 0;
                        waveProgressbar.setCurrent(0, 0 + "%");
                        handler.sendEmptyMessageDelayed(one, 2000);

                    }
                    break;`

**Comment by ShiraazMoollatjie** [comment]
Thanks. I think it's these two lines that make it work:
```
    waveProgressbar.setVisibility(View.GONE);
    waveProgressbar.setVisibility(View.VISIBLE);
```

Previously I had just ```waveProgressbar.setCurrent(0,"")``` but adding the above 2 lines did it for me.

**Comment by fpasxos** [comment]
You welcome.

**Comment by fpasxos** [comment]
You Welcome.
Exactly.The setCurrent just reloads the percentage ;)

**Comment by ShiraazMoollatjie** [comment]
Out of interest, there is another way to reset the percentage:

```
mWaveProgressView.setCurrent(0," ");
mWaveProgressView.requestLayout();
mWaveProgressView.invalidate();
```

Essentially, you're trying to call the ```onMeasure()``` method of the view lifecycle to reset the progress bar. This is done by calling ```requestLayout()``` on the view. If you use just ```invalidate()```, then you call the ```onDraw()``` method which does not cause a reset.

I'm adding this because it is easier for me to understand from a lifecycle perspective (I used to work in Flex which has a similar UI rendering concept). I also find it a less "magical" alternative than making the view disappear and reappear. 

Thanks so much for a great Android UI Widget. I learnt so much from it :)
